### ISSUE TITLE
ISSUE_HA-010:  2014-12-03  HA County - Stormwater Concept Design Sites conflict w/ TREE SITE SELECTION

### ISSUE THREAD

**Issue by kerrymcmahon** [rmeitl/TMDL-Sites--Conflict-Resolution#13]
**WHAT** - There are 2 concept design (final stage) stormwater sites in HARFORD county that are "in concept design" after a field review. These sites cannot be changed at this time.

**CONFLICT** -  TREE SITE SELECTION sites that are "recommended for Restoration," 

**ACTION NEEDED** -  Tree team must update either the status or geometry of the TREE SITE SELECITON sites. Issue cannot be closed until these are update in the TMDL database.

**SHAPE LOCATION** - The master geodatabase is located on Projectwise - The feature name matches the issue name, ISSUE_HA_010

pw:\SHAVMPWX.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\GIS Updates\2014-11-17-Backlog_Conflicts\2014_Stormwater_Tree_Conflicts_Database.zip

**NOTE** - The issues feature represents that stormwater footprint. These **must** be viewed with the TREE SITE SELECTION and LUCHANGE_BMP featureclassses.

**Comment by SRF-NMP** [comment]
Since these are in Tree Site Selection and "recommended for restoration," if the Tree team could please move these to future consideration and not be moved to a contract (making appropriate updates in the TMDL database) because the BMP sites are already in CD and cannot be changed, that'd be great Thanks!

**Comment by kerrymcmahon** [comment]
Brittany has update the TREE_SITE_SELECTION featureclass to make these sites "Future Consideration." This issue is considered closed.

**Comment by kerrymcmahon** [comment]
QC'd and reconfirmed on 01/06
