### ISSUE TITLE
ISSUE_HA_012 -  2014-12-07 HA County - Stormwater Recommended for Restoration sites conflict w/ TREE SITE SELECTION recommended sites

### ISSUE THREAD

**Issue by kerrymcmahon** [rmeitl/TMDL-Sites--Conflict-Resolution#14]
**WHAT** - There are 2 planned stormwater sites in HARFORD county that are "recommended for restoration" after desktop evaluation - they have not been visited in the field. 

**CONFLICT** -  TREE_SITE_SELECTION sites that are "recommended for restoration"

**ACTION NEEDED** -  Stormwater teams must rework sites that are overlapping, and be aware of sites that are within 15 feet of existing plantings.

**SHAPE LOCATION** - The master geodatabase is located on Projectwise - The feature name matches the issue name, ISSUE_HA_012

pw:\SHAVMPWX.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\GIS Updates\2014-11-17-Backlog_Conflicts\2014_Stormwater_Tree_Conflicts_Database.zip

**NOTE** - The issues feature represents that stormwater footprint. These **must** be viewed with the TREE SITE SELECTION and LUCHANGE_BMP featureclassses.

**Comment by SRF-NMP** [comment]
Tree Team,
1. SS_ID 1200335AUT barely overlaps with EFF_BMP_PLANNED b70baee8-3f85-4d14-9990-59218cbd9d6e. Could this SS_ID be reshaped to avoid the potential BMP footprint? It appears that this area can easily accommodate both trees and SWM.  
2. SS_ID 1200422BUT barely overlaps with EFF_BMP_PLANNED 9645ab63-dddf-40f2-adfb-be8b811f25d8. Could this SS_ID be reshaped to avoid the potential BMP footprint? It appears that this area can easily accommodate both trees and SWM.  Also, please verify that the other overlapping SS_ID 1200089UT is not built in the area of this potential BMP footprint (status is built) - this is part of a very large tree footrpint area that does not appear to have been refined to reflect the actual tree planting footprint.
Thanks!

**Comment by SRF-NMP** [comment]
Just checking in on this - can these be reshaped? I'd like to notify the consultant soon. Thanks so much!

**Comment by nbyers1** [comment]
Hi all,

Tree sites 1200335AUT and 1200422BUT have been reshaped to have a 10' buffer from the recommended stormwater sites.

In addition, Tree Site 1200089UT has been split into 1200089AUT and 1200089BUT to reflect the planted and unplanted areas according to the planting shapes in LUCHANGE_BMP. 1200089BUT, which intersects proposed SWM features, has been updated to have a status of 'Removed from Consideration'. (Note: lack of plantings was confirmed using Google Street View.)

Thanks,
Natalie

**Comment by kerrymcmahon** [comment]
Natalie, I am assuming this is in a checkout and I will see these changes within a few weeks, once pushed. I will check back in to close the issue.

**Comment by nbyers1** [comment]
Kerry,

The edits are in the RKK version of the TMDL database, which should be pushed up to OED each Friday. If you ever want to see the edits sooner, let me and/or Brittany know so that the edits can be pushed through earlier in the week.

**Comment by kerrymcmahon** [comment]
This issue is now closed. Thanks!
