### ISSUE TITLE
ISSUE_WA_013: 2014-12-08 WA County - - Washington County Concept Design sites conflict with TREE SITEL SELECTION

### ISSUE THREAD

**Issue by kerrymcmahon** [rmeitl/TMDL-Sites--Conflict-Resolution#15]
**WHAT** - This issue contains all sites in Washington County that have moved into concept design.

**CONFLICT** - The LUCHANGE conflicts have been resolved by email. they involve only slight reshaping.  There are some conflicts with TREE_SITE_SELECTION

**ACTION NEEDED** - Tree team must change all TREE_SITE_SELECITON sites that overlap with these 29 concepts to "future consideration" (if not already)

**SHAPE LOCATION** - The master geodatabase is located on Projectwise - The feature name matches the issue name, ISSUE_WA+013

pw:\SHAVMPWX.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\GIS Updates\2014-11-17-Backlog_Conflicts\2014-12-08-Unresolved_Conflicts.zip

**NOTE** - The issues feature represents that stormwater footprint. These **must** be viewed with the TREE SITE SELECTION and LUCHANGE_BMP featureclassses.

**Comment by nbyers1** [comment]
Six 'Recommend for Restoration' polygons in TREE_SITE_SELECTION intersected with the Issue 13 SWM shapefile. Brittany has updated those sites to 'Future Consideration' in the database.

**Comment by kerrymcmahon** [comment]
This issue is closed. I have verified these changes are reflected in the database.

**Comment by kerrymcmahon** [comment]
QC'd and reconfirmed on 01/06
