### ISSUE TITLE
ISSUE_AA_014 - 2014-12-15 AA County - Stormwater Recommended for Restoration sires conflict w/ LUCHANGE sites

### ISSUE THREAD

**Issue by kerrymcmahon** [rmeitl/TMDL-Sites--Conflict-Resolution#16]
**WHAT** - There are 12 planned stormwater sites in Anne Arundel county that are "recommended for restoration" after desktop evaluation - they have not been visited in the field. These are mainly "disconnection of non-rooftop runoff" credit - not actual structures, so it's likely these can be easily resolved.

**CONFLICT** -  LUCHANGE_BMP sites that are in a contract for 2015.

**ACTION NEEDED** -  Stormwater teams **must** rework sites that are overlapping, and be aware of sites that are within 15 feet of existing plantings.

**SHAPE LOCATION** - The master geodatabase is located on Projectwise - The feature name matches the issue name, ISSUE_AA_014

pw:\SHAVMPWX.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\GIS Updates\2014-11-17-Backlog_Conflicts\2014_Stormwater_Tree_Conflicts_Database.zip

**NOTE** - The issues feature represents that stormwater footprint. These **must** be viewed with the TREE SITE SELECTION and LUCHANGE_BMP featureclassses.

**Comment by SRF-NMP** [comment]
Hi All,
Since the AA Mapbook is to be published today (2014/01/09, as mentioned in Issue 15), I will wait to check these shapes against those in the mapbook GIS file before sending out tree boundaries that need to be avoided for this Issue to the consultants. Tree Team, could you please let me know when/where the GIS file is once it is ready? Thanks!

**Comment by nbyers1** [comment]
Hi Susan,

The geodatabase for the Anne Arrundel Mapbook sites is here:
pw:\shavmpwx.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\Tree Plantings\District 5\2015 Contract\01_SiteSelection\GIS\AA_FA14_toBHuber_01082015.zip

Within the geodatabase, the sites that are moving forward are in the feature class called 'AA_YES_Sites_20141217'.

-Natalie

**Comment by SRF-NMP** [comment]
Tree Team,

Can the footprint for tree site STRU_ID 020119UT be reshaped to accommodate the BMP sites noted below? There is only a minor overlap of the tree site and EFF_BMP_PLANNED_IDs bb4740c0-7501-467d-8a90-5a762e103342 and 3cce5932-3e0f-4915-a215-8e6ba33e5d56 (grass swales). This tree site does not appear in the Mapbook. The remainder of sites in this issue are disconnection credits, and I will notify the consultant.

**Comment by nbyers1** [comment]
Hi all,

STRU_ID 020119UT will be reshaped to avoid the SWM BMPs. I've sent the updated geometry to Brittany for entry into the database.

**Comment by kerrymcmahon** [comment]
This issue is closed.
