### ISSUE TITLE
ISSUE_WA_019 - 2015-01-02 WA County EFF_BMP_PLANNED that conflict with existing EFF_BMP_PLANNED from Group 1

### ISSUE THREAD

**Issue by kerrymcmahon** [rmeitl/TMDL-Sites--Conflict-Resolution#22]
**WHAT** - There are 2 planned stormwater sites in Washington County that are "recommended for restoration" after desktop evaluation - it has not been visited in the field. 

**CONFLICT** - EFF_BMP_PLANNED site in concept design - WA_ CEI_010 and WA_CE_023

**ACTION NEEDED** -  RKK WA County - Group 2 needs to remove or reshape their two sites that conflict with the sites from Group 1. These resulted because they reviewed shapes in very close proximity to shapes previously reviewed.

**SHAPE LOCATION** - The master geodatabase is located on Projectwise - The feature name matches the issue name, ISSUE_BA_019

pw:\SHAVMPWX.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\GIS Updates\2014-11-17-Backlog_Conflicts\2014_Stormwater_Tree_Conflicts_Database.zip

**Comment by SRF-NMP** [comment]
Kerry,
Thanks -there are two sites in this Issue in WA county, but they do not conflict with LUCHANGE.  Is there one that is supposed to be in this set that conflicts with LUCHANGE? Thanks!

**Comment by SRF-NMP** [comment]
Kerry, 
Since one site (023) was already removed, the only remaining site (010) conflicts with WA Co Mapbook stru_id 210396UT that was published 2014-01-05. I will wait to notify consult of need to reshape once final tree site shape is integrated into the updated LUCHANGE. Thanks!

**Comment by kerrymcmahon** [comment]
The concept package for 019 has already been submitted.
