### ISSUE TITLE
ISSUE_WA_020 - 2015-01-02 WA County EFF_BMP_LANNED recommended sites that conflict with LUCHANGE_BMP existing sites

### ISSUE THREAD

**Issue by kerrymcmahon** [rmeitl/TMDL-Sites--Conflict-Resolution#23]
**WHAT** - There are 37 planned stormwater sites in Washington Counrty that are "recommended for restoration" after desktop evaluation - they have not been visited in the field. 

**CONFLICT** -  LUCHANGE BMP existing sites

**ACTION NEEDED** -   Stormwater and tree teams can investigate the status of each site and reshape or change status as needed. Not all will need modification, depending on the status.

**SHAPE LOCATION** - The master geodatabase is located on Projectwise - The feature name matches the issue name, ISSUE_WA_020

pw:\SHAVMPWX.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\GIS Updates\2014-11-17-Backlog_Conflicts\2014_Stormwater_Tree_Conflicts_Database.zip

**NOTE** - The issues feature represents that stormwater footprint. These **must** be viewed with the TREE SITE SELECTION and LUCHANGE_BMP featureclassses.

**Comment by nbyers1** [comment]
Hi all,

There are 34 LUCHANGE BMP sites in conflict with the Issue WA 20 SWM BMPs. I am working with Brittany to have most of these deleted from LUCHANGE_BMP. There are three exceptions:

i) STRU_ID 210189UT has a status of 'NB', and is therefore not a real conflict. No action taken for this site.
ii) STRU_ID 210278UT - The conflict between the tree site and the SWM site looks fairly minor to me. Would it be possible to split the tree site to give space for the SWM BMP? If so, do you have any suggestion regarding how far east of the BMP the site should be split?
iii) STRU_ID 210324UT - The conflict between the tree site and the SWM site looks fairly minor to me. Would it be possible to split the tree site to give space for the SWM BMP? If so, do you have any suggestion regarding how far east of the BMP the site should be split? 

Thanks,
Natalie

**Comment by SRF-NMP** [comment]
Natalie,
Thank you very much for looking at these! A 50' buffer would be preferable since this is preliminary, and the footprint may change once it is visited in the field. Is that possible?

**Comment by nbyers1** [comment]
A 50' buffer has been applied for sites 210278UT and 210324UT.

**Comment by SRF-NMP** [comment]
Thanks, Natalie!

**Comment by kerrymcmahon** [comment]
I will close this issue when reflected in the DB. Thanks all.

**Comment by kerrymcmahon** [comment]
This issue is now closed/.
