### ISSUE TITLE
ISSUE_WA_021 - 2015-01-02 WA County EFF_BMP_PLANNED recommended sites that conflict with TREE SITE SELECTION

### ISSUE THREAD

**Issue by kerrymcmahon** [rmeitl/TMDL-Sites--Conflict-Resolution#24]
**WHAT** - There are 37 planned stormwater sites in Washington that are "recommended for restoration" after desktop evaluation - they have not been visited in the field. 

**CONFLICT** -  TREE_SITE_SELECTION recommended or reserved sites 

**ACTION NEEDED** -   Stormwater and tree teams can investigate the status of each site and reshape or change status as needed.

**SHAPE LOCATION** - The master geodatabase is located on Projectwise - The feature name matches the issue name, ISSUE_WA_021

pw:\SHAVMPWX.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\GIS Updates\2014-11-17-Backlog_Conflicts\2014_Stormwater_Tree_Conflicts_Database.zip

**NOTE** - The issues feature represents that stormwater footprint. These **must** be viewed with the TREE SITE SELECTION and LUCHANGE_BMP featureclassses.

**Comment by SRF-NMP** [comment]
Tree Team,
Since these are in TSS, could the ones that are recommended for restoration please be either marked for future consideration or reshaped with buffers in order to accommodate the SW footprints? It appears others are classified as removed from consideration. Thanks!

**Comment by nbyers1** [comment]
All of the conflicting TREE_SITE_SELECTION recommended sites for this issue have been changed to Future Consideration. (Edits are in the RKK version of the TMDL database.)

**Comment by kerrymcmahon** [comment]
These changes are not yet reflected in the database, so I will re-visit this issue in one week.

**Comment by kerrymcmahon** [comment]
This issue is now closed.
