### ISSUE TITLE
ISSUE_WA_024: 2014-02-09 - WAS County Concept Design Stormwater Site conflicts with LUCHANGE "in concept design" site

### ISSUE THREAD

**Issue by kerrymcmahon** [rmeitl/TMDL-Sites--Conflict-Resolution#27]
**WHAT** - There is 1 stormwater site in Washington County that is moving to design and has a pending BMP request form with MDE. 

**CONFLICT** -  EFF_BMP_PLANNED site that has been in concept and gone to design is conflicting with LUCHANGE site that is now showing as "in concept design". At the time these stormwater sites went into design, there was no conflict - they had been cleared to move ahead.

**ACTION NEEDED** - Tree teams should remove this site from consideration. The stormwater site has already been submitted and has a pending BMP request form with MDE.

**SHAPE LOCATION** - The master geodatabase is located on Projectwise - The feature name is PLANNING_CONFLICT_LOCATIONS, The issue number is ISSUE_WA_024.

pw:\SHAVMPWX.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\GIS Updates\2014-11-17-Backlog_Conflicts\2014_Stormwater_Tree_Conflicts_Database.zip

**Comment by nbyers1** [comment]
Kerry,

This is one of the sites I sent to Brittany to have removed from the LUCHANGE_BMP layer for Issue WA_020. At our last meeting, she mentioned that removing sites from LUCHANGE_BMP was turning out to be more time-consuming than expected, so it may simply be that the change has not yet been made. I'll email her to check on its status and report back.

Thanks,
Natalie

**Comment by kerrymcmahon** [comment]
Good to know!! Thanks! I will check back in a day or two.

**Comment by SRF-NMP** [comment]
Thanks, Natalie. I emailed Gwen about this area. It is also in the Mapbook BMP conflicts with ss_id 2100362AUT.

**Comment by kerrymcmahon** [comment]
The site is still in design concept. I will recheck in a week.

**Comment by kerrymcmahon** [comment]
This site is still appearing in concept design. I will check again in a week.

**Comment by kerrymcmahon** [comment]
I am still seeing this as "in design concept".

**Comment by kerrymcmahon** [comment]
This issue is now closed.
