### ISSUE TITLE
ISSUE_BA_025: 2015-02-15 BA County - Stormwater Concept site site conflict w/ LUCHANGE "proposed" site under contract AT0685282

### ISSUE THREAD

**Issue by kerrymcmahon** [rmeitl/TMDL-Sites--Conflict-Resolution#28]
**WHAT** - There is 1 stormwater CONCEPT site in Baltimore County that has moved through concept design and is being sent to design. This somehow made it in without getting picked up as a conflict. The tree site was not moved into this contract until  January 03, 2015. These stormwater sites were run for conflicts last year.

**CONFLICT** -  LUCHANGE site "proposed" in contract

**ACTION NEEDED** -  Teams must discuss options for this site.

**SHAPE LOCATION** - The master geodatabase is located on Projectwise - The feature name is PLANNING_CONFLICT_LOCATIONS, The issue number is ISSUE_WA_025

pw:\SHAVMPWX.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\GIS Updates\2014-11-17-Backlog_Conflicts\2014_Stormwater_Tree_Conflicts_Database.zip

**NOTE** - The PLANNING_CONFLICT_LOCATION feature represents the location of the conflict. These **must** be viewed with the LUCHANGE_BMP, TREE SITE SELECTION and EFF_BMP_PLANNED featureclassses.

**Comment by nbyers1** [comment]
Kerry,

While I don't expect it will affect the outcome here - according to the tree site's Gen_Com, the site was brought in on January 3, 2013, not 2015. 

I'll discuss the issue with the rest of the Tree Team.

Thanks,
Natalie

**Comment by kerrymcmahon** [comment]
Ah good catch. Yeah, I am not sure what happened with this one. We will deal with whatever the outcome. Thanks for looking into this.

**Comment by nbyers1** [comment]
SWM team, 

Can you supply us with a construction footprint? We'll revise the tree site to avoid planting within the SWM construction footprint.

Thanks,
Natalie

**Comment by kerrymcmahon** [comment]
I will email the concept plans shortly

**Comment by kerrymcmahon** [comment]
The file is too large to email. PLEASE open as "read only"

the page number is: 90

pw:\SHAVMPWX.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\Baltimore\Gr1-MTI\08-Submissions\2014-12-12-BA Co CD-MT-Submission-1\2014-12-12-BA Co-MT-Submission 1-Concept report-plans.pdf

**Comment by gwengibs** [comment]
Hi,
I'm looking at modifying the site.  We may be able to squeeze in some trees depending on how far away you want us to stay away from the LOD?  or does the LOD already build in a buffer around the grading/ staging activities?
Thanks

**Comment by SRF-NMP** [comment]
Gwen,

We are requesting a 50' buffer. Thanks!

**Comment by kerrymcmahon** [comment]
Please let me know when the tree shape has been modified.

**Comment by kerrymcmahon** [comment]
What is the status of this update? The tree site is still the original shape.

**Comment by nbyers1** [comment]
My understanding of the situation is this:

Gwen called Susie and discussed whether a smaller buffer was possible. Gwen is waiting to hear back from Susie for a final determination of what buffer will be necessary.

I am checking in with Gwen weekly to find out if we have a final number for the buffer.

**Comment by SRF-NMP** [comment]
Tree Team,

The shape shown in GIS appears to be only that of the footprint, and not the LOD. The LOD footprint in the CD submittal actually extends approximately 80' to the north and 50' to the west of the footprint that is seen in GIS. Can a tree site still work in the approximate available area?

**Comment by SRF-NMP** [comment]
The CD plans are located here if you'd like to see the limits of the LOD on PDF page 303/784 (Site 033) :
pw:\shavmpwx.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\Baltimore\Gr1-MTI\08-Submissions\2015-02-10-BA CD-MT-Resubmission01\2015-02-10-BA Co-MT-Resubmission 1-Concept report-plans.pdf

Thanks!

**Comment by nbyers1** [comment]
SWM Team,

The question we were asking was: Is the LOD final? Or do we need to use a buffer from the LOD shown in the PDF? If we can use the LOD as given in the concept design, then we can fit trees in the rest of the site. However, if we were to apply a 50' buffer BEYOND the LOD, as the original response to Gwen would indicate, then we'd have to abandon almost the entire site.

Thanks,
Natalie

**Comment by SRF-NMP** [comment]
This LOD as shown in the PDF may change when it is carried to final design since this is only concept design, so yes, the buffer is needed beyond the LOD shown in the PDF. I'm assuming that you are only able to see the grading footprint in GIS, and not the LOD as shown in the PDF of the CD report? Just want to make sure you are able to see the actual LOD, and not simply the grading footprint from CD.
Thanks!

**Comment by nbyers1** [comment]
In GIS, we have only the grading footprint. The LOD we would need to approximate from the PDF.

To be clear: you definitely need a 50' buffer (a smaller buffer would not suffice) from the CD LOD?

**Comment by SRF-NMP** [comment]
Yes, that is correct. Thanks!

**Comment by nbyers1** [comment]
Sorry for never updating on this - BA00286, aka STRU_ID 030242UT, was NOT planted this season and has been removed from consideration.

**Comment by kerrymcmahon** [comment]
This issue is now closed.
