### ISSUE TITLE
ISSUE_AA_026: 2015-02-16 AA County - Stormwater Field Reviewed sites conflict with TREE SITE SELECTION "under review" sites

### ISSUE THREAD

**Issue by kerrymcmahon** [rmeitl/TMDL-Sites--Conflict-Resolution#29]
**WHAT** - There are 4 stormwater sites reviewed in the field in AA county 

**CONFLICT** -  conflict with TREE SITE SELECTION sites that are UNDER REVIEW

**ACTION NEEDED** - This group already lost 45 sites to the NPS ownership on 295. It is imperative that they do not lost any more sites. Tree team, please accommodate these footprints if possible.

**SHAPE LOCATION** - The master geodatabase is located on Projectwise - The feature name is PLANNING_CONFLICT_LOCATIONS, The issue number is ISSUE_AA_026

pw:\SHAVMPWX.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\GIS Updates\2014-11-17-Backlog_Conflicts\2014_Stormwater_Tree_Conflicts_Database.zip

**Comment by nbyers1** [comment]
Hi all,

For three of the four conflicts, the TREE SITE SELECTION polygon has been updated to 'Future Consideration' in the RKK version of the database.

However, the fourth conflict is not just a conflict with a TREE SITE SELECTION polygon - it is also in conflict with one of our LUCHANGE polygons, a Reserve site for the upcoming spring planting season (Spring 2015). This conflict was captured in ISSUE_AA_014. I will discuss with the rest of the Tree Team what the appropriate course of action is for this site and comment again shortly.

Thanks,
Natalie

**Comment by SRF-NMP** [comment]
Natalie,

Thanks - can SITE_NAME 0201629AUT (from Issue 14) be slightly reshaped in order to accommodate EFF_BMP_PLANNED_ID bb4740c0-7501-467d-8a90-5a762e103342 (AAGr2-WTB-052)?

Susie

**Comment by nbyers1** [comment]
Hi Susie,

STRU_ID 020119UT (site name 0201629AUT) will be reshaped to avoid the SWM BMPs. I've sent the corrected geometry to Brittany for entry into the database.

-Natalie

**Comment by kerrymcmahon** [comment]
Issue closed once the other three sites are updated.

**Comment by SRF-NMP** [comment]
Natalie, thanks for doing this!

**Comment by kerrymcmahon** [comment]
This issue is now closed
