### ISSUE TITLE
ISSUE_PG_028: PG county Stormwater desktop reviewed sites conflict with TREE SITE SELECTION "recommended for restoration" sites

### ISSUE THREAD

**Issue by kerrymcmahon** [rmeitl/TMDL-Sites--Conflict-Resolution#30]
**WHAT** - There are 2 stormwater sites reviewed at the desktop only

**CONFLICT** -  conflict with TREE SITE SELECTION sites that are "Recommended for Restoration"

**ACTION NEEDED** - Teams work together to reshapes sites accordingly

**SHAPE LOCATION** - The master geodatabase is located on Projectwise - The feature name is PLANNING_CONFLICT_LOCATIONS, The issue number is ISSUE_PG_28

pw:\SHAVMPWX.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\GIS Updates\2014-11-17-Backlog_Conflicts\2014_Stormwater_Tree_Conflicts_Database.zip

**Comment by SRF-NMP** [comment]
Tree Team,

SS_ID 1602102UT overlaps with EFF_BMP_PLANNED_IDs fef31da2-b6a3-4207-bb8b-503216a28818 and 8ab23224-09f3-4f77-b84d-0953ebb04b02. Could the tree site be moved to FC in order to accommodate the potential BMPs? They are scheduled to be visited in the field next week, depending on weather. Thanks!

**Comment by nbyers1** [comment]
SWM Team,

SS_ID 1602102UT can and will be moved to FC. I'll comment again when it has been updated.

Thanks,
Natalie

**Comment by nbyers1** [comment]
SS_ID 1602102UT has been changed to FC. This edit will be visible when the RKK version edits are next pushed through to the main database version.

**Comment by kerrymcmahon** [comment]
I will update next week when I see the changes.

**Comment by SRF-NMP** [comment]
Natalie - thanks! PG county is looking tough for good SWM sites, so it is much appreciated!

**Comment by kerrymcmahon** [comment]
This issue is now closed.
