### ISSUE TITLE
ISSUE_CL_027: 2015-02-16 CL County Stormwater sites conflict with TREE SITES SELECTION "Recommended for Restoration" sites

### ISSUE THREAD

**Issue by kerrymcmahon** [rmeitl/TMDL-Sites--Conflict-Resolution#31]
**WHAT** - There are 27 stormwater sites reviewed in the field in Carroll County 

**CONFLICT** -  conflict with TREE SITE SELECTION sites that are "Recommended for Restoration"

**ACTION NEEDED** - Some conflicts are complete overlaps. Others are minor. Minor ones should be able to be reworked so that both teams can pursue treatment.

**SHAPE LOCATION** - The master geodatabase is located on Projectwise - The feature name is PLANNING_CONFLICT_LOCATIONS, The issue number is ISSUE_CL_027

pw:\SHAVMPWX.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\GIS Updates\2014-11-17-Backlog_Conflicts\2014_Stormwater_Tree_Conflicts_Database.zip

**Comment by nbyers1** [comment]
Kerry,

I am unable to find polygons for the conflicting SWM features in EFF_BMP_PLANNED to determine if sites should be reshaped or entirely set aside. Is there a separate file containing the CL SWM sites with which this conflict was run?

Thanks,
Natalie

**Comment by kerrymcmahon** [comment]
I will be postinga new database in about 15 minutes.

**Comment by kerrymcmahon** [comment]
pw:\SHAVMPWX.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\GIS Updates\2014-11-17-Backlog_Conflicts\2014_Stormwater_Tree_Conflicts_Database.zip

The new database is posted. Remember, the issues are located in the point featureclass PLANNING_CONFLICT_LOCATIONS.

**Comment by SRF-NMP** [comment]
Is this for Group 2?

**Comment by nbyers1** [comment]
Hi all,

All conflicting TREE SITE SELECTION sites have either been edited to avoid conflict or changed to FC. These edits should be visible when the RKK version edits are next pushed through to the main database version.

Thanks,
Natalie

**Comment by SRF-NMP** [comment]
Thanks, Natalie!

**Comment by kerrymcmahon** [comment]
Group 2. 
I will update this issue once I see changes reflected in the DB.

**Comment by kerrymcmahon** [comment]
This issue is now closed.
