### ISSUE TITLE
CONFLICT_00002: CL-Grp2-RKK DE sites

### ISSUE THREAD

**Issue by jseipp** [rmeitl/TMDL-Sites--Conflict-Resolution#35]
WHAT - 14 stormwater DESKTOP EVALUTION sites (CL-Grp2-RKK) in Carroll County that are adjacent to tree planting sites to be planted in Spring 2015 (STRU_ID = 060051UT, 060053UT, 060055UT, 060072UT, 060073UT, 060077UT, 060078UT, and 060091UT).

CONFLICT – LUCHANGE site 

ACTION NEEDED – The stormwater DE sites need to be removed prior to advancing to FIELD INVESTIGATION

**Comment by kerrymcmahon** [comment]
The TMDL database has been updated to reflect the sites moving to "Future Consideration." Email sent to Kristin to notify consultant. Data posted on PW: pw:\SHAVMPWX.shacadd.ad.mdot.mdstate:SHAEDMS01\Documents\Areawide Projects\AW-82 TMDL\02 Implementation & Monitoring\SWM\New BMPs\Carroll\Gr2-RKK\07-GIS\SHA Review\20150423_Sites_For_Removal.zip

Site will be closed once consultant has confirmed

**Comment by SRF-NMP** [comment]
Should shapes be reshaped/reclassified as FC instead of RC?
Thanks!

**Comment by jseipp** [comment]
The shapes were reclassified as FC not RC and therefore "removed" from the consultant's list of potential sites to visit in the field. They were not completely removed from the list. Sorry for the confusion. I have sent an email to the consultant and am waiting for confirmation from them that they are no longer considering them for field investigation.

**Comment by jseipp** [comment]
The consultant responded with the following:

"Thank you for providing this information below.  Please note that we have already completed our field investigation stage of this task and provided our results to SHA last Tuesday, 4/21.  However, in order to better understand the conflicts you have mentioned and to ensure that we agree that they exist, we have looked at the 17 sites you identified in more detail.  Of the 17 sites (we could only find 16 in the file), we have visited 9 of them during our field investigation.  In the attached spreadsheet, you will see our comments. 

To summarize:
· The footprint for 3 out of 9 field investigated sites were re-drawn during the FI so that impacts are no longer anticipated.
· For 3 out of 9 field investigated sites there appears to be sufficient space for a facility based on field observed white flagging (generally 25 to 30’ width) without impacting the tree assets. Our recommendation would be to keep these site under consideration rather than move them to FC.
· 1 of the 9 field investigated sites was recommended for FC because impacts to tree assets could not be avoided.
· 1 of the 9 field investigated sites does not appear to impact tree assets.  Attached a screen shot.  It is for site RKK-048.
· 1 of 9 field investigated sites was recommended for a grass swale, however, it probably should have been recommended for FC based on field observation.  There was 35’ width between the roadway and the tree assets based on the GIS data but according to the field form the white flagging was 12’ from the roadway, which indicates that there is likely not enough room for both a swale and the tree assets unless the tree assets are reduced in size.  Attached a screen shot of this site which is RKK -050.
· Of the remaining 7 that were not field investigated, 3 may qualify as existing grass swale credit (should still be evaluated), 1 we do not agree with changing to FC, 1 would need slight modification to avoid conflict, and 2 we would agree with changing to FC.

Please see the attached spreadsheet for details and let us know if you would like to discuss any sites in detail.  As mentioned above, the FI stage is complete, so any sites that are changed to FC will just need to be noted so that we do not carry to concept design.

**NOTE:** Attachments from consultant are available if needed.

**Comment by kerrymcmahon** [comment]
This issue is now closed. Consultant has change 47A, 47B and 50 to FC. All other sites will remain as consultant is aware of proximity.
