### ISSUE TITLE
CONFLICT_00001: WA-Grp1-CEI-001 CD site adjacent to 210015UT (ongoing)

### ISSUE THREAD

**Issue by jseipp** [rmeitl/TMDL-Sites--Conflict-Resolution#36]
WHAT - There is 1 stormwater CONCEPT site in Washington County that is adjacent to an existing tree site that is under and active maintenance contract. Depending on the approach selected for design, the stormwater site could impact the tree site.

CONFLICT - LUCHANGE_BMP 

ACTION NEEDED - Attached is a mark up showing the potential impact to the tree site. The teams need to discuss the various options and evaluate which scenario will provide the TMDL program with the greatest amount of credit.
![2015-04-23-cei001-markup-ksl](https://cloud.githubusercontent.com/assets/11890203/7302039/89c24152-e9b4-11e4-94b8-8e12c0d367f5.jpg)

**Comment by nbyers1** [comment]
Hi all, 
The Tree team is looking into what info we have on the site. It may be one we are planning a field visit to in the coming year to see whether survival was even high enough to count. We'll let you know when we've found some answers.

**Comment by jseipp** [comment]
Do you have more information on when a site visit is scheduled and/or the status of the tree planting currently? Is it possible to make a site visit to this tree planting site a priority? This site is at concept design and we need to know whether it is should be considered for design or not. If the trees are not doing well and we have the opportunity to move forward with a SWM project there to get more treatment it would be helpful to know that.

**Comment by nbyers1** [comment]
It looks like the site is not slated to be visited until next year to determine its survival status. At a quick guess based on the image above, we'd lose about 0.15 acres of tree plantings (at 0.38 areas of impervious treatment to each acre of tree planting, that's worth 0.06 acres of impervious area treatment) within the red line. Would the project extend beyond the red line? I assume you expect to get considerably more treatment than what trees would be losing - if that's the case, we're willing to edit our polygon and let SWM use the area.

**Comment by jseipp** [comment]
To provide everyone with an update:
This BMP site has moved on to final design.  We are going to let the design team see if they can rework this area to first avoid the trees.  If they can't, they will do a more thorough look at the trade off between trees and SWM - survey will help with this.

This should be a couple months down the road, which sounds like will still before the tree team gets out there to inspect, so we should be ok.  We will continue to keep everyone updated as we explore the project further.
