### ISSUE TITLE
LUCHANGE_BMP - CONFLICT_10010: CL-Grp2-RKK - Tree Planting site from 2013

### ISSUE THREAD

**Issue by kerrymcmahon** [rmeitl/TMDL-Sites--Conflict-Resolution#42]
**WHAT** There is a LUCHANGE polygon CL100 that conflicts with a new BMP footprint, but site appears not to be planted.

**SITE NAME**
CL-GRP2-RKK-018

**ACTION** Emailed tree team to inquire about status of site. Awaiting repsonse.

![conflict_10010](https://cloud.githubusercontent.com/assets/9559830/7394100/82b1e4ee-ee5f-11e4-9890-8c7cf7045f83.JPG)
![conflict_10010_b](https://cloud.githubusercontent.com/assets/9559830/7394102/8480e3e2-ee5f-11e4-96c7-f8d2689ce27c.JPG)

**Comment by nbyers1** [comment]
Hi all,

This site is one marked as 'really needs clean-up' in our database! We're hoping to get out and visit it this season to mark out the real boundaries. 

That aside, the Tree Team sees no problem with SWM proceeding with the site. Please make sure to keep us updated on the final site geometry so we can incorporate that into our site boundary edits when we make those.

**Comment by kerrymcmahon** [comment]
Thanks Natalie! We will allow the team to proceed. For now, assume that the footprint shown there is accurate. We can provide new copies of the featureclass whenever you need. This footprint won't change unless it moves to concept design, at which point I will provide the update. This issue is now closed.
