### ISSUE TITLE
(Ongoing) LUCHANGE_BMP - CONFLICT_10011: CL-Grp2-RKK - Tree Planting site 

### ISSUE THREAD

**Issue by kerrymcmahon** [rmeitl/TMDL-Sites--Conflict-Resolution#43]
**WHAT** There is a LUCHANGE polygon CL1068R that conflicts with a new BMP footprint, but site appears not to interfere during recent field visit. The eastern-most portion that overlaps with the stormwater site does not have existing trees, only low scrub and grass.

**SITE NAME**
CL-GRP2-RKK-026

**ACTION** - Please verify field conditions and see if we can allow stormwater team to move forward.

Please notify if further data is needed

![conflict-10011](https://cloud.githubusercontent.com/assets/9559830/7394417/690cfa2c-ee61-11e4-9d66-c6955d1dba8c.JPG)
![conflict-10011b](https://cloud.githubusercontent.com/assets/9559830/7394440/8ef3dd0a-ee61-11e4-95d6-20420c65880e.JPG)

**Comment by nbyers1** [comment]
Hi all,

This site is not slated to be field verified any time soon. However, if the SWM field team is confident that there are no trees in the area that would be impacted, we're content to modify the site shape to avoid conflict with the new SWM feature.

**Comment by nbyers1** [comment]
Also - what do you need to consider this conflict resolved? I could edit the shape exactly to meet the edge of the currently proposed BMP, I can apply a 10' offset, etc.

**Comment by kerrymcmahon** [comment]
Don't worry about changing the shape until we get a concept plan. If they see trees, they would revise their plan, but from the last go, there were no tree reported. We will submit the latest footprint when it's available. I will keep this issue open to remind us to update you accordingly.
