### ISSUE TITLE
CONFLICT_00004: WA-GRP1-CEI-055 conflicts with LUCHANGE_BMP Site 210258UT

### ISSUE THREAD

**Issue by jseipp** [rmeitl/TMDL-Sites--Conflict-Resolution#44]
**WHAT:** A new BMP is being evaluated for inclusion in a Final Design package. The footprint for the site overlaps with LUCHANGE_BMP Site 210258UT which has a status of "In Design Concept".

**SITE NAME:** WA-GRP1-CEI-055

**ACTION:** Please verify the status and footprint of this project. If the project is moving forward, please provide the planned installation date.

![conflict_00004](https://cloud.githubusercontent.com/assets/11890203/7749158/0c6cb2f0-ff99-11e4-8f1c-2bf7909de796.JPG)

**Comment by nbyers1** [comment]
Hi all,

This site has just entered the design stage. The footprint you see is the most up-to-date footprint; however, it is quite possible that the site's footprint could change during the design phase as ROW data, utility information, and other comments are received. 

The anticipated AD date for this site's contract (contract # = WA2775182) is 5/3/16, and the sites would be planted over the following three planting seasons (Fall 2016, Spring  2017, and Fall 2017).

I believe it should not be a problem to remove this site from the cohort currently in design for WA county. Please let me know if that is the best option.

Thanks,
Natalie

**Comment by kerrymcmahon** [comment]
This stormwater site appears to not have moved into final design. I am placing it on hold for now. We might look at it again down the road, but there is no need to adjust or remove the tree site at this time. I will now consider this issue closed.
